Do not treat API errors as unwanted resources
When an API has not even been used in a project the commands fail and
log something like the following:

ERROR: (gcloud.compute.backend-services.list) HTTPError 403: Access
Not Configured.

Let's not treat it as if we found a resource, but let's not hide the
message either.